// cs-diagnosis.test.js — tripwire for the frozen CS shape-gate diagnosis
// (tools/data/cs-diagnosis-report.json, generated by
// tools/broadband/cs-diagnose.js on the v2-anchor cs-pipeline baseline).
// Locks the decomposition numbers so silent drift turns the suite red and
// re-derives the headline identity (shipped short-period bias == pure-HF
// bias) for one case from first principles.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const r = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-diagnosis-report.json'), 'utf8'));

test('cs-diagnosis — schema and basis frozen', () => {
  assert.equal(r.schema, 'quake-sim-cs-diagnosis-v1');
  assert.equal(r.basis.sourceModel, 'quake-sim-psha-source-v2');
  assert.ok(r.basis.note.includes('DIAGNOSIS ONLY'));
  assert.ok(r.basis.arms.includes('A1 hfOnly'));
  assert.ok(r.basis.pipeline.includes('gates frozen FAIL'));
});

test('cs-diagnosis — frozen decomposition numbers locked', () => {
  assert.equal(r.aggregate.shipped01Median, 0.634);
  assert.equal(r.aggregate.hfOnly01Median, 0.634); // == shipped: the overshoot is entirely the Boore HF side
  assert.equal(r.aggregate.kappa04Delta01Median, -0.186);
  assert.equal(r.aggregate.nCasesTargetBelowAll01s, 4); // osaka+kochi: mixture target unreachable at 0.1 s
  assert.equal(r.aggregate.nCasesTargetAboveAll3s, 0);  // 3 s target sits INSIDE the bin envelope everywhere
  assert.deepEqual(r.aggregate.kochi24sBias, [[-0.555, -0.58, -0.47], [-0.418, -0.298, -0.27]]);
  assert.deepEqual(r.aggregate.halfspaceEffect24sKochi, [[-0.016, 0.004, 0.039], [0.01, -0.011, 0.075]]);
});

test('cs-diagnosis — per-case identities', () => {
  assert.equal(r.cases.length, 6); // sendai skipped (no JIVSM column, frozen)
  for (const c of r.cases) {
    // A1 identity: shipped short-band bias equals the pure-HF bias (the LP'd
    // LF tail above 2 Hz is not bit-zero — rounding differences up to 0.01)
    for (let i = 0; i < c.shortBand.shippedBias.length; i++) {
      assert.ok(Math.abs(c.shortBand.shippedBias[i] - c.shortBand.hfOnlyBias[i]) <= 0.01,
        c.site.id + ' RP' + c.rp + ' idx' + i + ': shipped ' + c.shortBand.shippedBias[i] + ' vs hfOnly ' + c.shortBand.hfOnlyBias[i]);
    }
    // structural arms exist only for the 2-5 s offenders
    if (c.site.id === 'kochi' || c.site.id === 'osaka') {
      assert.ok(c.structural && c.structural.halfspaceVsJivsm);
      // JIVSM column is NOT the cause: |halfspace effect| <= 0.08 at every period
      assert.ok(c.structural.halfspaceVsJivsm.every((v) => Math.abs(v) <= 0.08), c.site.id + ' halfspace effect too large');
      // Q is NOT the cause: |q100 effect| <= 0.005 at every period
      assert.ok(c.structural.q100VsQ50.every((v) => Math.abs(v) <= 0.005), c.site.id + ' Q effect too large');
    }
  }
  const kochi475 = r.cases.find((c) => c.site.id === 'kochi' && c.rp === 475);
  assert.equal(kochi475.targetReachability.targetBelowAllBins, true);
  assert.equal(kochi475.targetReachability.targetAboveAllBins3s, false);
});

test('cs-diagnosis — tokyo hfOnly bias recomputable (drift guard)', () => {
  const hybrid = require(path.join(__dirname, '..', 'tools', 'broadband', 'hybrid.js'));
  const Physics = require(path.join(__dirname, '..', 'public', 'physics.js'));
  const jivsmCols = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'public', 'geojson', 'jivsm-columns.json'), 'utf8'));
  Physics.setJivsmColumns(jivsmCols);
  const cal = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'broadband-hybrid-calibration.json'), 'utf8'));
  const frozen = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-pipeline-report.json'), 'utf8'));
  const anchorIdx = frozen.preRegistered.periodsSec.indexOf(frozen.preRegistered.anchorPeriodSec);
  const kochi = r.cases.find((c) => c.site.id === 'kochi' && c.rp === 475);
  assert.ok(kochi, 'kochi RP475 case');

  // rebuild ONE hfOnly realization deterministically: source = the frozen
  // pipeline's dominant-bin realization for kochi RP475 (mw/rRup recorded)
  const src = frozen.realizations.find((x) => x.site === 'kochi' && x.rp === 475 && x.arm === 'hybrid' && x.i === 0);
  assert.ok(src, 'frozen kochi source realization');
  const col = Physics.jivsmColumnAt(kochi.site.lat, kochi.site.lng);
  const stack = hybrid.buildJivsmIaspStack(col);
  const targetMean = frozen.cases.find((c) => c.site.id === 'kochi' && c.rp === 475).mscs.meanGal;
  const out = hybrid.hybridSynthesis({
    sourceLat: src.psaGal ? kochi.site.lat : kochi.site.lat, // receiver at site; source reconstructed from the recorded geometry
    sourceLng: kochi.site.lng, sourceDepthKm: src.depthKm,
    mw: src.mw, strike: src.strike, dip: 15, rake: 90,
    receiverLat: kochi.site.lat, receiverLng: kochi.site.lng, vs30: 400,
    stack, lfMaxHz: 0.001, stressMPa: cal.chosenStressMPa, kappaSec: cal.chosenKappaSec,
    sampleRateHz: 50, seed: 20260904
  });
  const gal = out.transverse.map((a) => a * 100);
  const psa = Physics.sdofResponseSpectrum(gal, out.sampleRateHz, frozen.preRegistered.periodsSec, 0.05).map((x) => x.psaGal);
  const ratio = Math.log10(psa[0] / psa[anchorIdx]) - Math.log10(targetMean[0] / targetMean[anchorIdx]);
  // the frozen hfOnly median (0.471) is a median over sampled bins; a single
  // reconstruction from the recorded dominant bin must land within 0.35 log10
  assert.ok(Math.abs(ratio - kochi.shortBand.hfOnlyBias[0]) < 0.35,
    'kochi hfOnly@0.1s drift: single-bin ' + ratio.toFixed(3) + ' vs frozen median ' + kochi.shortBand.hfOnlyBias[0]);
});

// ===========================================================================
//  cs-diagnosis v2 (2026-09-15, PRE_REG_V5): band-shape ownership on the
//  SHIPPED SH-only v3/v4 baseline, after the CS v4 execution refuted the
//  missing-P-SV hypothesis. Frozen by `node tools/broadband/cs-pipeline.js
//  --v5-diag`. The amendment field is part of the record: the pre-registered
//  eps clause turned out inapplicable on the frozen v4 rows.
// ===========================================================================
const d2 = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-diagnosis-v2-report.json'), 'utf8'));
const v4 = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-pipeline-v4-report.json'), 'utf8'));

test('cs-diagnosis-v2 — pre-registration and audit verdict frozen', () => {
  assert.equal(d2.schema, 'quake-sim-cs-diagnosis-v2');
  assert.ok(d2.preRegistered.batch.includes('cs-diagnose-v2'));
  assert.deepEqual(d2.preRegistered.thresholds, { ownership: 0.8, targetAuditMaxDelta: 0.02, seamDeviation: 0.1, stressSpreadMax: 2, stressResidualMax: 0.15 });
  const a = d2.targetAudit;
  assert.equal(a.nRows, 150);
  assert.equal(a.verdict, 'PASS: no construction bug');
  assert.ok(a.maxMuDelta <= 0.02 && a.maxMuDelta > 0.004, 'maxMuDelta ' + a.maxMuDelta + ' must sit in its measured band');
  // the amendment IS the record: epsBin does not exist on the v4 rows
  assert.equal(a.epsClauseApplicable, false);
  assert.equal(a.nEpsChecked, 0);
  assert.ok(a.amendment.includes('INAPPLICABLE') && a.amendment.includes('subsumes eps'));
});

test('cs-diagnosis-v2 — partition ownership, dead stress lever, seam', () => {
  assert.equal(d2.attribution.short.owner, 'HF');
  assert.equal(d2.attribution.short.hfShare, 1); // the fcHz=1 Hz hard partition, in numbers
  assert.ok(d2.stressFeasibility.verdict.startsWith('DEAD'), 'the Brune-corner stress lever must stay registered DEAD');
  assert.equal(d2.stressFeasibility.postHocMax, 0.53);
  assert.equal(d2.attribution.seamFlagged, false);
  const sStar = d2.stressFeasibility.perCaseSstar.map((x) => x.Sstar);
  assert.deepEqual(sStar, [0, 0, 0, null, null, null]); // the lever cannot even reach the band in half the cases
});

test('cs-diagnosis-v2 — full-arm consistency with the frozen v4 report + long-band sign split', () => {
  for (const c of d2.cases) {
    const p = v4.perCase.find((x) => x.arm === 'hybrid' && x.site === c.site && x.rp === c.rp);
    assert.ok(p, 'v4 perCase row missing for ' + c.site);
    assert.deepEqual(c.biasLog10.full, p.biasLog10, c.site + ' full-arm bias must equal the frozen v4 numbers');
  }
  const g = (site) => d2.cases.filter((c) => c.site === site).map((c) => c.biasLog10.full[12]);
  for (const v of g('kochi')) assert.ok(v < -0.3, 'kochi long band must stay a deficit, got ' + v);
  for (const v of g('osaka')) assert.ok(v > 0.45, 'osaka long band must stay an excess, got ' + v);
  // D4: the v3-fitted LF gain tilt owns only a minor share of the LF shape excess
  for (const c of d2.cases) {
    const tilt = c.biasLog10.D2_lfOnly[12] - c.biasLog10.D4_lfNoGain[12];
    assert.ok(tilt >= 0.09 && tilt <= 0.31, 'gain tilt at 5s out of measured band: ' + tilt);
  }
});

// ===========================================================================
//  cs-diagnosis v3 (2026-09-15, PRE_REG_V6): column-swap causality + tilt
//  decomposition. Frozen by `node tools/broadband/cs-pipeline.js --v6-diag`.
//  Amendment of record: the first v6 run's U was anchor-level contaminated
//  (untilted@1s = eps*sigma(1s) != 0); the frozen run scores SHAPE
//  (untilted minus the anchor offset), which the untiltedShape[7]==0 lock
//  pins forever.
// ===========================================================================
const d3 = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-diagnosis-v3-report.json'), 'utf8'));

test('cs-diagnosis-v3 — tilt decomposition frozen (shape-only, synthesis-side)', () => {
  assert.equal(d3.schema, 'quake-sim-cs-diagnosis-v3');
  assert.deepEqual(d3.preRegistered.thresholds, { columnOwnsMin: 0.6, sourceOwnsMax: 0.4, untiltedMax: 0.15 });
  assert.ok(d3.tiltDecomposition.U > 0.3 && d3.tiltDecomposition.U < 0.33, 'U ' + d3.tiltDecomposition.U + ' must sit in its measured band');
  assert.ok(d3.tiltDecomposition.verdict.startsWith('SYNTHESIS-SIDE'), 'the shape-only verdict must stay SYNTHESIS-SIDE');
  for (const c of d3.tiltDecomposition.cases) {
    // the shape correction is exact: at the anchor the shape bias is zero
    assert.equal(c.biasLog10.untiltedShape[7], 0, c.site + ' untiltedShape@1s must be exactly 0');
    assert.ok(c.biasLog10.untilted[7] > 0.17 && c.biasLog10.untilted[7] < 0.54, 'anchor offset in measured band');
    assert.ok(c.anchorOffsetLog10 > 0.17 && c.anchorOffsetLog10 < 0.54);
  }
});

test('cs-diagnosis-v3 — column swap: the frozen reversal rule says SOURCE-OWNED', () => {
  const cs = d3.columnSwap;
  assert.deepEqual([cs.Dorig, cs.Dswap, cs.columnOwns], [0.914, 0.552, 0.198]);
  assert.ok(cs.verdict.startsWith('SOURCE-OWNED'), 'the pre-registered reversal rule verdict must stay on record');
  // descriptive (not the rule): the linear column share is ~40%
  const lin = +((cs.Dorig - cs.Dswap) / cs.Dorig).toFixed(2);
  assert.ok(lin >= 0.35 && lin <= 0.45, 'linear column share ' + lin + ' out of measured band');
});

test('cs-diagnosis-v3 — arbiter reference carried for the population contrast', () => {
  assert.ok(d3.arbiterReference, 'the frozen arbiter numbers must ride along');
  assert.equal(d3.arbiterReference.DSYN['0.2'], -0.238);
  assert.ok(d3.arbiterReference.disclosure.includes('NOT identical'), 'the configuration confound must stay disclosed');
});

// ===========================================================================
//  cs-align-retest v1 (2026-09-15..16, PRE_REG_V7) + CS_GATE_ROLE: the
//  research-line closure. The shipped configuration on REAL events lands
//  on the observed shapes; the class split and the scenario-population
//  marginal are the frozen structure of the short-band FAIL.
// ===========================================================================
const ar = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-align-retest-report.json'), 'utf8'));

test('cs-align-retest — pre-registered verdict frozen (CONFIG-OWNED at the letter)', () => {
  assert.equal(ar.schema, 'quake-sim-cs-align-retest-v1');
  assert.equal(ar.aggregate.alignedDs02, 0.02);
  assert.ok(ar.aggregate.verdict.startsWith('CONFIG-OWNED'), 'the R1 verdict must stay on record');
  assert.equal(ar.aggregate.alignedDs['0.1'], -0.147);
  assert.equal(ar.preRegistered.references.legacyArbiterBruneArmDs['0.2'], -0.238, 'the legacy cold anchor rides along');
  assert.equal(ar.events.length, 13);
  for (const e of ar.events) assert.equal(e.nTimeout, 0, 'no station hit the 90 s wall budget');
});

test('cs-align-retest — class split frozen (crustal warm, interplate/intraslab cold)', () => {
  const by = (cls) => ar.events.filter((e) => e.srcType === cls).map((e) => e.alignedDs['0.2']);
  const med = (a) => {
    const s2 = a.slice().sort((x, y) => x - y);
    const m = s2.length >> 1;
    return s2.length % 2 ? s2[m] : (s2[m - 1] + s2[m]) / 2;
  };
  assert.ok(Math.abs(med(by('crustal')) - 0.071) < 0.001);
  assert.ok(Math.abs(med(by('interplate')) - (-0.265)) < 0.001);
  assert.ok(Math.abs(med(by('intraslab')) - (-0.1425)) < 0.001);
});

test('CS_GATE_ROLE — the closure statement frozen', () => {
  const role = require('../tools/broadband/cs-pipeline.js').CS_GATE_ROLE;
  assert.equal(role.revised, '2026-09-16 (CS research line closure)');
  assert.ok(role.shortBand.disposition.includes('KILLED by the pre-registered G3'), 'the candidate must stay on record as measured-dead, not pending');
  assert.ok(role.shortBand.disposition.includes('OPPOSITE SIGNS'), 'the population-contrast mechanism must stay named');
  assert.ok(role.shortBand.finding.includes('alignedDs(0.2s) = +0.02'), 'the v7 measured anchor must appear');
  assert.ok(role.longBand.disposition.includes('no global LF cure exists'));
  assert.ok(role.production.includes('MEASURED-NO-CURE'), 'the P-SV retirement must stay linked');
});

// ===========================================================================
//  PRE_REG_V8 (2026-09-17, user-scheduled): the per-class kappa cure,
//  fitted on real events (G1 pass) and KILLED by the pre-registered G3
//  scenario non-regression gate. G2 was moot per the registration (any
//  FAIL -> NEGATIVE, nothing wired). kappa stays global 0.04.
// ===========================================================================
const kbc = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-kappa-by-class.json'), 'utf8'));
const ksc = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-kappa-scenario-report.json'), 'utf8'));

test('PRE_REG_V8 — the fit and its kill are frozen', () => {
  assert.equal(kbc.schema, 'quake-sim-cs-kappa-by-class-v1');
  assert.equal(kbc.G1.pass, true);
  assert.deepEqual([kbc.classes.interplate.kappa, kbc.classes.crustal.kappa, kbc.classes.intraslab.kappa], [0.01783, 0.04595, 0.02671]);
  // the first draft had the physical sign inverted (it "passed" G1 against
  // its own wrong-sign model) — the frozen model text carries the correction
  assert.ok(kbc.preRegistered.model.includes('physical sign'));
  assert.equal(ksc.schema, 'quake-sim-cs-kappa-scenario-v1');
  assert.equal(ksc.pass, false);
  assert.deepEqual([ksc.bandsOld.short, ksc.bandsNew.short], [0.776, 0.96]);
  assert.deepEqual([ksc.bandsOld.long, ksc.bandsNew.long], [0.574, 0.777]);
});