// cs-diagnosis.test.js — tripwire for the frozen CS shape-gate diagnosis
// (tools/data/cs-diagnosis-report.json, generated by
// tools/broadband/cs-diagnose.js on the v2-anchor cs-pipeline baseline).
// Locks the decomposition numbers so silent drift turns the suite red and
// re-derives the headline identity (shipped short-period bias == pure-HF
// bias) for one case from first principles.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const r = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-diagnosis-report.json'), 'utf8'));

test('cs-diagnosis — schema and basis frozen', () => {
  assert.equal(r.schema, 'quake-sim-cs-diagnosis-v1');
  assert.equal(r.basis.sourceModel, 'quake-sim-psha-source-v2');
  assert.ok(r.basis.note.includes('DIAGNOSIS ONLY'));
  assert.ok(r.basis.arms.includes('A1 hfOnly'));
  assert.ok(r.basis.pipeline.includes('gates frozen FAIL'));
});

test('cs-diagnosis — frozen decomposition numbers locked', () => {
  assert.equal(r.aggregate.shipped01Median, 0.634);
  assert.equal(r.aggregate.hfOnly01Median, 0.634); // == shipped: the overshoot is entirely the Boore HF side
  assert.equal(r.aggregate.kappa04Delta01Median, -0.186);
  assert.equal(r.aggregate.nCasesTargetBelowAll01s, 4); // osaka+kochi: mixture target unreachable at 0.1 s
  assert.equal(r.aggregate.nCasesTargetAboveAll3s, 0);  // 3 s target sits INSIDE the bin envelope everywhere
  assert.deepEqual(r.aggregate.kochi24sBias, [[-0.555, -0.58, -0.47], [-0.418, -0.298, -0.27]]);
  assert.deepEqual(r.aggregate.halfspaceEffect24sKochi, [[-0.016, 0.004, 0.039], [0.01, -0.011, 0.075]]);
});

test('cs-diagnosis — per-case identities', () => {
  assert.equal(r.cases.length, 6); // sendai skipped (no JIVSM column, frozen)
  for (const c of r.cases) {
    // A1 identity: shipped short-band bias equals the pure-HF bias (the LP'd
    // LF tail above 2 Hz is not bit-zero — rounding differences up to 0.01)
    for (let i = 0; i < c.shortBand.shippedBias.length; i++) {
      assert.ok(Math.abs(c.shortBand.shippedBias[i] - c.shortBand.hfOnlyBias[i]) <= 0.01,
        c.site.id + ' RP' + c.rp + ' idx' + i + ': shipped ' + c.shortBand.shippedBias[i] + ' vs hfOnly ' + c.shortBand.hfOnlyBias[i]);
    }
    // structural arms exist only for the 2-5 s offenders
    if (c.site.id === 'kochi' || c.site.id === 'osaka') {
      assert.ok(c.structural && c.structural.halfspaceVsJivsm);
      // JIVSM column is NOT the cause: |halfspace effect| <= 0.08 at every period
      assert.ok(c.structural.halfspaceVsJivsm.every((v) => Math.abs(v) <= 0.08), c.site.id + ' halfspace effect too large');
      // Q is NOT the cause: |q100 effect| <= 0.005 at every period
      assert.ok(c.structural.q100VsQ50.every((v) => Math.abs(v) <= 0.005), c.site.id + ' Q effect too large');
    }
  }
  const kochi475 = r.cases.find((c) => c.site.id === 'kochi' && c.rp === 475);
  assert.equal(kochi475.targetReachability.targetBelowAllBins, true);
  assert.equal(kochi475.targetReachability.targetAboveAllBins3s, false);
});

test('cs-diagnosis — tokyo hfOnly bias recomputable (drift guard)', () => {
  const hybrid = require(path.join(__dirname, '..', 'tools', 'broadband', 'hybrid.js'));
  const Physics = require(path.join(__dirname, '..', 'public', 'physics.js'));
  const jivsmCols = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'public', 'geojson', 'jivsm-columns.json'), 'utf8'));
  Physics.setJivsmColumns(jivsmCols);
  const cal = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'broadband-hybrid-calibration.json'), 'utf8'));
  const frozen = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'tools', 'data', 'cs-pipeline-report.json'), 'utf8'));
  const anchorIdx = frozen.preRegistered.periodsSec.indexOf(frozen.preRegistered.anchorPeriodSec);
  const kochi = r.cases.find((c) => c.site.id === 'kochi' && c.rp === 475);
  assert.ok(kochi, 'kochi RP475 case');

  // rebuild ONE hfOnly realization deterministically: source = the frozen
  // pipeline's dominant-bin realization for kochi RP475 (mw/rRup recorded)
  const src = frozen.realizations.find((x) => x.site === 'kochi' && x.rp === 475 && x.arm === 'hybrid' && x.i === 0);
  assert.ok(src, 'frozen kochi source realization');
  const col = Physics.jivsmColumnAt(kochi.site.lat, kochi.site.lng);
  const stack = hybrid.buildJivsmIaspStack(col);
  const targetMean = frozen.cases.find((c) => c.site.id === 'kochi' && c.rp === 475).mscs.meanGal;
  const out = hybrid.hybridSynthesis({
    sourceLat: src.psaGal ? kochi.site.lat : kochi.site.lat, // receiver at site; source reconstructed from the recorded geometry
    sourceLng: kochi.site.lng, sourceDepthKm: src.depthKm,
    mw: src.mw, strike: src.strike, dip: 15, rake: 90,
    receiverLat: kochi.site.lat, receiverLng: kochi.site.lng, vs30: 400,
    stack, lfMaxHz: 0.001, stressMPa: cal.chosenStressMPa, kappaSec: cal.chosenKappaSec,
    sampleRateHz: 50, seed: 20260904
  });
  const gal = out.transverse.map((a) => a * 100);
  const psa = Physics.sdofResponseSpectrum(gal, out.sampleRateHz, frozen.preRegistered.periodsSec, 0.05).map((x) => x.psaGal);
  const ratio = Math.log10(psa[0] / psa[anchorIdx]) - Math.log10(targetMean[0] / targetMean[anchorIdx]);
  // the frozen hfOnly median (0.471) is a median over sampled bins; a single
  // reconstruction from the recorded dominant bin must land within 0.35 log10
  assert.ok(Math.abs(ratio - kochi.shortBand.hfOnlyBias[0]) < 0.35,
    'kochi hfOnly@0.1s drift: single-bin ' + ratio.toFixed(3) + ' vs frozen median ' + kochi.shortBand.hfOnlyBias[0]);
});
