'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Strong=require('../public/strong-motion-data.js');
const Physics=require('../public/physics.js');
function waveform(id){const component=channel=>({channel,samples:[0,1,2,1,0,-1,-2,-1,0],sha256:'a'.repeat(64)});return {_schema:'quake-sim-waveform-v1',units:'gal',sampleRateHz:100,station:{id},components:{z:component('HNZ'),n:component('HNN'),e:component('HNE')},quality:{researchReady:true,responseRemoved:true,sourceGapCount:0,deliveryResampled:false},provenance:{provider:'NIED',sourceUrl:'https://example.org/data',retrievedAt:'2026-08-01T00:00:00Z'}};}
function fixture(){return {_schema:Strong.SCHEMA,event:{id:'test',mw:7,lat:35,lng:140,depthKm:10,originTime:'2026-01-01T00:00:00Z',sourceUrl:'https://example.org/event'},provenance:{provider:'NIED K-NET/KiK-net',sourceUrl:'https://example.org',license:'terms',retrievedAt:'2026-08-01T00:00:00Z'},quality:{frozen:true,requireSurfaceBoreholePairs:true},records:[{stationId:'ABC-s',siteId:'ABC',locationType:'surface',sensorDepthM:0,station:{lat:35,lng:140},waveform:waveform('ABC-s')},{stationId:'ABC-b',siteId:'ABC',locationType:'borehole',sensorDepthM:100,station:{lat:35,lng:140},waveform:waveform('ABC-b')}]};}
test('frozen response-corrected surface/borehole event is research-ready',()=>{const result=Strong.validate(fixture());assert.equal(result.valid,true);assert.equal(result.researchReady,true);assert.equal(result.pairs.length,1);});
test('missing borehole pair blocks research certification without invalidating K-NET data',()=>{const payload=fixture();payload.records.pop();const result=Strong.validate(payload);assert.equal(result.valid,true);assert.equal(result.researchReady,false);assert.ok(result.warnings.includes('no-surface-borehole-pairs'));});
test('event analysis reports intensity PGA PGV spectra and duration',()=>{const result=Strong.analyze(fixture(),Physics);assert.equal(result.records.length,2);for(const row of result.records){assert.ok(Number.isFinite(row.intensity));assert.ok(row.pgaVectorGal>0);assert.ok(row.pgvVectorCms>0);assert.ok(row.duration5to95Sec>=0);assert.ok(row.spectra.x.length>0);}});
